// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsgoxqhbkvjppspqwjzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZ294cWhia3ZqcHBzcHF3anp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MDM1ODksImV4cCI6MjA1NjA3OTU4OX0.zDUNUDj_y-GR223d5CpubvV8DJo-3JclVy-oeK_YQRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);